export const COOKIE_NAME='NEXTJS-SERVER-COOKIENAME'
export const SECRET_COOKIE_PASSWORD='?j?sRU=r#rQxXYzw^xHq72%#44fLxtJ&zwf2?K5?82w8KcSE'
export const GOOGLE_MAPS_API_KEY='AIzaSyCsFYRiFbltQGQTFnRT_yvgpcg0Z0SS57Q';